services:
  - type: web
    name: portfolio-chatbot
    env: python
    plan: free
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && uvicorn main_prod:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    disk:
      name: portfolio-chatbot-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
